apiVersion: v1
kind: Service
metadata:
  name: moviecrudsql
  labels:
    run: moviecrudsql
spec:
  type: ClusterIP
  ports:
  - port: 9602
    targetPort: 3602
    protocol: TCP
  selector:
    app: moviecrudsql